### ISSUE TITLE
In ruby 2.3.1 getting undefined method `deg2rad' (related to issue #97)

### ISSUE THREAD

**Issue by helmutrs** [topfunky/gruff#146]
I am getting this error with ruby 2.3.1, any suggestions?

**Comment by donv** [comment]
I'll have a look at running with Ruby 2.3.1 this weekend.

**Comment by donv** [comment]
Hi @helmutrs !

Tests are now running with MRI 2.3.1 and JRuby 9.1.2 in travis-ci.  no error like you mentioned.

Could you try with master from GitHub?

**Comment by donv** [comment]
@helmutrs are you using the latest gruff release?

**Comment by Watson1978** [comment]
Now, seems Gruff has worked well with Ruby 2.3 and later on CI.
I think it is time to close this issue.

Feel free to reopen this if you needed.
